README.md
composer.json
composer.lock

Release Dec 16

---

includes/newspack-listings-utils.php
src/assets/front-end/curated-list.scss
src/assets/shared/curated-list.scss
src/assets/shared/variables.scss
src/blocks/curated-list/block.json
src/blocks/curated-list/edit.js
src/blocks/curated-list/editor.scss
src/blocks/curated-list/view.php
src/blocks/listing/editor.scss
src/components/sidebar-query-controls.js
src/editor/utils.js

Release Dec 18

---

includes/class-newspack-listings-block-patterns.php
includes/class-newspack-listings-blocks.php
newspack-listings.php

Alpha release Feb 02

---

includes/class-newspack-listings-block-patterns.php
includes/class-newspack-listings-blocks.php
newspack-listings.php

Release Feb 09

---

src/blocks/curated-list/edit.js
src/blocks/list-container/edit.js
src/blocks/listing/edit.js

Release Jun 08

---

includes/class-newspack-listings-core.php
includes/newspack-listings-utils.php

A new beta release with some features to mitigate the potential impact if the plugin needs to be reverted to v1.

Beta release: Phase 2 initial features (2)

---

.distignore
src/blocks/list-container/edit.js

Release Jun 22

---

includes/class-newspack-listings-core.php
includes/class-newspack-listings-taxonomies.php
includes/importer/class-newspack-listings-importer.php
includes/migration/class-newspack-listings-migration.php
newspack-listings.php

A new alpha release for the beta test-in-progress, including fixes for potential memory leaks stemming from the utilities to handle legacy terms.

Beta release

---

src/blocks/listing/listing.js
src/editor/shadow-taxonomies/child-listings.js
src/editor/shadow-taxonomies/parent-listings.js

Alpha release Jul 06

---

src/blocks/listing/listing.js
src/editor/shadow-taxonomies/child-listings.js
src/editor/shadow-taxonomies/parent-listings.js

Release Jul 06

---

includes/class-newspack-listings-core.php
includes/newspack-listings-utils.php
src/blocks/event-dates/edit.js
src/blocks/listing/listing.js
src/editor/utils.js
src/templates/listing.php

Alpha release Aug 03

---

includes/class-newspack-listings-core.php
includes/newspack-listings-utils.php
src/blocks/event-dates/edit.js
src/blocks/listing/listing.js
src/editor/utils.js
src/templates/listing.php

Release Aug 03

---

includes/class-newspack-listings-core.php

Alpha release Aug 10

---

includes/class-newspack-listings-core.php

Release Aug 10

---

.distignore
includes/class-newspack-listings-api.php
includes/class-newspack-listings-core.php
includes/class-newspack-listings-settings.php
includes/importer/class-newspack-listings-importer.php
src/templates/listing.php

Alpha release Sep 08

---

.distignore
includes/class-newspack-listings-api.php
includes/class-newspack-listings-core.php
includes/class-newspack-listings-settings.php
includes/importer/class-newspack-listings-importer.php
src/templates/listing.php

Release Sep 08

---

includes/class-newspack-listings-core.php
includes/class-newspack-listings-products.php
includes/class-newspack-listings-settings.php
includes/newspack-listings-utils.php
src/assets/front-end/archives.scss
src/assets/front-end/view.scss
src/blocks/event-dates/edit.js
src/blocks/event-dates/editor.scss

Alpha release Sep 21

---

includes/class-newspack-listings-core.php
includes/class-newspack-listings-products.php
includes/class-newspack-listings-settings.php
includes/newspack-listings-utils.php
newspack-listings.php
src/assets/front-end/archives.scss
src/assets/front-end/view.scss
src/blocks/event-dates/edit.js
src/blocks/event-dates/editor.scss

Release Sep 21

---

includes/class-newspack-listings-core.php
includes/class-newspack-listings-settings.php

Release Oct 19

---

.circleci/config.yml
includes/class-newspack-listings-api.php
includes/class-newspack-listings-blocks.php
includes/class-newspack-listings-featured.php
includes/class-newspack-listings-taxonomies.php
includes/newspack-listings-utils.php
newspack-listings.php
src/blocks/curated-list/edit.js
src/blocks/curated-list/index.js
src/blocks/event-dates/index.js
src/blocks/list-container/index.js
src/blocks/listing/edit.js
src/blocks/price/index.js
src/editor/featured-listings/index.js
src/editor/index.js
tests/bootstrap.php
tests/test-featured.php

Alpha release Nov 01

---

.circleci/config.yml
includes/class-newspack-listings-api.php
includes/class-newspack-listings-blocks.php
includes/class-newspack-listings-featured.php
includes/class-newspack-listings-taxonomies.php
includes/newspack-listings-utils.php
newspack-listings.php
src/blocks/curated-list/edit.js
src/blocks/curated-list/index.js
src/blocks/event-dates/index.js
src/blocks/list-container/index.js
src/blocks/listing/edit.js
src/blocks/price/index.js
src/editor/featured-listings/index.js
src/editor/index.js
tests/bootstrap.php
tests/test-featured.php

Release Nov 02

---

src/assets/front-end/self-serve-listings.scss
src/assets/front-end/view.scss
src/assets/shared/self-serve-listings.scss
src/assets/shared/variables.scss
src/blocks/index.js
src/blocks/self-serve-listings/block.json
src/blocks/self-serve-listings/edit.js
src/blocks/self-serve-listings/editor.scss
src/blocks/self-serve-listings/index.js
src/blocks/self-serve-listings/view.php
src/editor/index.js
src/templates/self-serve-form.php

Alpha release Nov 09

---

src/assets/front-end/self-serve-listings.scss
src/assets/front-end/view.scss
src/assets/shared/self-serve-listings.scss
src/assets/shared/variables.scss
src/blocks/index.js
src/blocks/self-serve-listings/block.json
src/blocks/self-serve-listings/edit.js
src/blocks/self-serve-listings/editor.scss
src/blocks/self-serve-listings/index.js
src/blocks/self-serve-listings/view.php
src/editor/index.js
src/templates/self-serve-form.php

Release Nov 09

---

includes/class-newspack-listings-products.php

While testing an unrelated feature that also involved purchasing WooCommerce products, I found that orders that didn't contain a listing product but did result in account creation were still getting swept up in the listing post creation process, and those accounts were still getting flagged as listing customers despite not having purchased one of the required products. This is happening because some of the checks we're using to check whether a purchase order includes listing products are a bit sloppy; some line item arrays need to be reindexed before using them in `in_array`.
This PR also implements a failsafe check that will stop the self-serve listing logic as early as possible if we find that none of line items in an order are a listing product.
1. Ensure that WooCommerce and WC …

fix: implement a failsafe check before flagging an order as a listing purchase

---

.circleci/config.yml
CHANGELOG.md
composer.lock
includes/class-newspack-listings-api.php
includes/class-newspack-listings-blocks.php
includes/class-newspack-listings-core.php
includes/class-newspack-listings-products.php
includes/newspack-listings-utils.php
newspack-listings.php
package-lock.json
package.json
src/assets/front-end/archives.js
src/assets/front-end/curated-list.js
src/assets/front-end/event.js
src/assets/front-end/patterns.js
src/assets/front-end/self-serve-listings.js
src/assets/index.js
webpack.config.js

Release Mar 08

---

composer.json
includes/class-featured.php
package-lock.json
package.json
src/assets/shared/self-serve-listings.scss
src/blocks/self-serve-listings/block.json
src/blocks/self-serve-listings/edit.js
src/templates/self-serve-form.php
tests/test-featured.php

Alpha release May 02

---

CHANGELOG.md
composer.json
includes/class-featured.php
newspack-listings.php
package-lock.json
package.json
src/assets/shared/self-serve-listings.scss
src/blocks/self-serve-listings/block.json
src/blocks/self-serve-listings/edit.js
src/templates/self-serve-form.php
tests/test-featured.php

Release May 02

---

includes/class-settings.php
package-lock.json
package.json

Alpha release May 30

---

CHANGELOG.md
newspack-listings.php
package-lock.json
package.json

Release Jul 25

---

.prettierrc
includes/class-api.php
includes/class-featured.php
package-lock.json
package.json
src/assets/front-end/curated-list.scss
src/assets/front-end/event.scss
src/assets/front-end/listing.scss
src/assets/front-end/patterns.scss
src/assets/front-end/self-serve-listings.scss
src/assets/front-end/view.scss
src/assets/shared/curated-list.scss
src/assets/shared/listing.scss
src/assets/shared/self-serve-listings.scss
src/blocks/curated-list/edit.js
src/blocks/curated-list/editor.scss
src/blocks/event-dates/editor.scss
src/blocks/listing/edit.js
src/blocks/listing/editor.scss
src/blocks/self-serve-listings/editor.scss
src/components/sidebar-query-controls.js
src/editor/featured-listings/index.js
src/editor/style.scss
src/editor/utils.js

Alpha release Aug 05

---

includes/class-api.php
includes/class-blocks.php
includes/class-featured.php
includes/utils.php
package-lock.json
package.json
src/editor/index.js

Alpha release Aug 12

---

.prettierrc
CHANGELOG.md
includes/class-api.php
includes/class-blocks.php
includes/class-featured.php
includes/utils.php
newspack-listings.php
package-lock.json
package.json
src/assets/front-end/curated-list.scss
src/assets/front-end/event.scss
src/assets/front-end/listing.scss
src/assets/front-end/patterns.scss
src/assets/front-end/self-serve-listings.scss
src/assets/front-end/view.scss
src/assets/shared/curated-list.scss
src/assets/shared/listing.scss
src/assets/shared/self-serve-listings.scss
src/blocks/curated-list/edit.js
src/blocks/curated-list/editor.scss
src/blocks/event-dates/editor.scss
src/blocks/listing/edit.js
src/blocks/listing/editor.scss
src/blocks/self-serve-listings/editor.scss
src/components/sidebar-query-controls.js
src/editor/featured-listings/index.js
src/editor/index.js
src/editor/style.scss
src/editor/utils.js

Release Aug 16

---

src/blocks/curated-list/block.json
src/blocks/curated-list/view.php

Alpha release Aug 26

---

CHANGELOG.md
newspack-listings.php
package-lock.json
package.json
src/blocks/curated-list/block.json
src/blocks/curated-list/view.php

Release Sep 14

---

composer.json
composer.lock
includes/class-blocks.php
includes/class-products.php
includes/class-settings.php
package-lock.json
package.json
src/blocks/self-serve-listings/view.php
tests/bootstrap.php

Alpha release Sep 26

---

CHANGELOG.md
composer.json
composer.lock
includes/class-blocks.php
includes/class-products.php
includes/class-settings.php
newspack-listings.php
package-lock.json
package.json
src/blocks/self-serve-listings/view.php
tests/bootstrap.php

Release Sep 27

---

.circleci/config.yml
composer.json
composer.lock
tests/test-blocks.php
tests/test-featured.php

Updates declared `phpunit` version to be in line with the rest of the repos.

chore: update phpunit version

---

.circleci/config.yml
composer.json
composer.lock
includes/class-products.php
includes/products/class-products-purchase.php
includes/products/class-products-ui.php
includes/products/class-products-user.php
package-lock.json
package.json
postcss.config.js
src/editor/index.js
tests/test-blocks.php
tests/test-featured.php

Alpha release Jan 13

---

.circleci/config.yml
composer.json
composer.lock
includes/class-products.php
includes/products/class-products-purchase.php
includes/products/class-products-ui.php
includes/products/class-products-user.php
package-lock.json
package.json
postcss.config.js
src/assets/shared/variables.scss
src/editor/index.js
tests/test-blocks.php
tests/test-featured.php

Alpha release Mar 01

---

composer.lock
languages/newspack-listings.pot
package-lock.json
package.json

Alpha release Jun 08

---

CHANGELOG.md
composer.lock
languages/newspack-listings.pot
newspack-listings.php
package-lock.json
package.json

Release Jun 19

---

composer.lock
includes/class-settings.php
package-lock.json
package.json
src/templates/event-dates.php

Alpha release Sep 06

---

CHANGELOG.md
composer.lock
includes/class-settings.php
newspack-listings.php
package-lock.json
package.json
src/templates/event-dates.php

Release Sep 13

---

CHANGELOG.md
composer.lock
languages/newspack-listings.pot
newspack-listings.php
package-lock.json
package.json

Release Oct 31

---

.circleci/config.yml
.hooks/pre-push
PULL_REQUEST_TEMPLATE.md
README.md
includes/importer/README.md
package-lock.json
package.json

1. Adds a new `epic/*` release workflow for creating release builds that we can use for beta testing and other QA purposes. This workflow is similar to `alpha` and `hotfix/*` workflows, but kind of in between them.
2. Renames the `master` branch to `trunk`.
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/2895, but for the Newspack Listings repo.

feat(ci): add epic/* release workflow and rename `master` to `trunk`

---

.circleci/config.yml
.hooks/pre-push
PULL_REQUEST_TEMPLATE.md
README.md
composer.lock
includes/importer/README.md
package-lock.json
package.json

Alpha release Feb 08
