includes/newspack-listings-utils.php, src/components/sidebar-query-controls.js
Fixes two minor bugs:
1. When syncing metadata, avoid a PHP warning when the `single` key is not set in the metadata config array. This happens when syncing metadata that supports syncing data from multiple instances of a block, and the metadata config array in the newspack-listings-core.php file doesn't include the `'single' key.
2. When creating a new list in Query mode, "Listing Type" is now available as a default Sort By option (as "Any" is the default listing type).
Closes #18.
1. Start out on the `master` branch.
2. Create a new Event listing post and add an a.) Event Dates block and b.) more than one Jetpack Contact Info block. Fill in data for all blocks.
3. Attempt to save or publish the post, and observe a PHP warning like `PHP Notice:  Undefined index: single in …
=> fix: minor bug fixes

includes/class-newspack-listings-core.php, includes/class-newspack-listings-settings.php, src/editor/sidebar/index.js
Adds a new global setting and post-level option to hide the publish (and modified, if enabled in the theme) dates from listings. Addresses publisher feedback that this should be a feature alongside the ability to show/hide authors.
* Requires https://github.com/Automattic/newspack-theme/pull/1359 in the theme to test template-level changes
* Requires https://github.com/Automattic/newspack-blocks/pull/762 to test with Homepage Posts and Post Carousel blocks (also fixes the display of listing authors if the "Hide authors" option is on)
Closes #55.
1. Check out the required theme and blocks branches mentioned above, along with this branch.
2. From WP admin, visit Listings > Settings and confirm a new global setting which is on by default:
3. Without changing the setting, visit any published …
=> feat: new global setting and post option to hide publish dates

src/blocks/listing/block.json, src/blocks/listing/edit.js
Fixes a bug introduced by #56 which broke Specific Listings mode in the Curated List block.
1. On `epic/phase-2`, create a Curated List block in Specific Listings mode and add a listing of any type.
2. Observe that no matter what listing you select, the block preview displays the latest published listing of any type (not necessarily matching the selected type).
3. Observe on the front-end that the list block shows no content.
4. Check out this branch, confirm that both issues with selecting and showing specific listings are fixed in both the editor and on the front-end.
=> fix: use value property of selection from AutocompleteWithSuggestions

src/blocks/curated-list/edit.js, src/blocks/list-container/edit.js, src/blocks/listing/edit.js
**NOTE:** Replaces #63, since it affects `master` as well.
Something must have changed in a recent Gutenberg release that broke the (admittedly hacky) method we were using to sync the parent Curated List block's attributes to its inner blocks. This PR updates the method to use `updateBlockAttributes` [as documented](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-block-editor/#updateBlockAttributes) for this purpose instead.
Also fixes a fetch loop in the editor that caused individual listing blocks to repeatedly fetch their posts via the REST API.
Closes #62.
1. On `master`, create a Curated List block and set to Specific Listings mode. Add several listings of any type.
2. In Dev Tools > Network, filter by XHR requests containing `v1/listings`. Observe that …
=> fix: syncing attributes from curated list block to inner blocks

includes/class-newspack-listings-core.php
#39 deprecated the custom categories and tags for listings in favor of regular post categories and tags. This might cause issues for sites that have been using this plugin up til now; after Phase 2 is released, these terms will no longer be visible in the admin or on the front-end. 
This PR runs a function on `admin_init` to convert legacy custom taxonomy terms to regular post categories and tags, and applies the new terms to any posts that had the legacy terms. Then, cleans up the legacy terms from the DB. Only runs on `admin_init` so that the queries don't execute on the front-end. After the conversion, all listings should display the same terms as before (so the change should be undetectable to readers), but those terms are now post categories and tags.
Closes #42.
1. On `master`, …
=> feat: convert legacy terms

.circleci/config.yml, bin/install-wp-tests.sh, includes/class-newspack-listings-blocks.php, package.json, phpunit.xml.dist, tests/bootstrap.php, tests/test-blocks.php
Adds a PHP test suite and hooks it up to CI for this repo. For now, it includes only some basic block rendering tests for the Curated List block, but this should lay the foundation for a more robust testing suite for other features as needed.
Closes #52.
Observe the tests and linters passing below.
=> test: init test suite

includes/class-newspack-listings-taxonomies.php
Fixes a few PHP warnings that are thrown when activating the plugin, due to unregistered taxonomies.
1. On `epic/phase-2`, deactivate and activate the plugin. Observe the following warnings being thrown on activation:
```
Warning: array_filter() expects parameter 1 to be array, object given in /Users/site/Local Sites/newspack/app/public/wp-content/plugins/newspack-listings/includes/class-newspack-listings-taxonomies.php on line 622
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/site/Local Sites/newspack/app/public/wp-content/plugins/newspack-listings/includes/class-newspack-listings-taxonomies.php on line 625
Warning: array_filter() expects parameter 1 to be array, object given in /Users/site/Local …
```
=> fix: PHP warning on plugin activation

includes/class-newspack-listings-api.php, includes/class-newspack-listings-core.php, includes/newspack-listings-utils.php, src/assets/shared/listing.scss, src/blocks/curated-list/edit.js, src/blocks/listing/edit.js, src/blocks/listing/listing.js, src/templates/listing.php
Adds support for Newspack Sponsors to listings, both on individual listing pages and in curated lists.
Closes #35.
1. Check out [this branch](https://github.com/Automattic/newspack-sponsors/pull/58) in the Newspack Sponsors repo. This lets the Listings plugin add support for sponsors to its own custom post types. Make sure you have at least one native and one underwriter sponsor published on your site.
2. Edit a listing of any type. Confirm there's now a "Sponsors" sidebar panel which lets you choose sponsors, just like on regular posts and pages.
3. Apply a native and an underwriter sponsor to the listing and update.
4. View the listing's front-end page. Confirm that both native and underwriter sponsors are shown as they would be on a regular post, whether or not the listing is set to …
=> feat: support Newspack Sponsors for listings

src/blocks/price/edit.js, src/blocks/price/editor.scss, src/blocks/price/index.js, src/blocks/price/view.php
I don't like the current style of the block when it's selected in the editor. This PR changes this to use `Placeholder`.
I'm also not sure why we need to use an `h2`, to me it doesn't make sense and we should be using a `p` with `has-large-font-size` (this could potentially even be a Setting in the sidebar? Maybe combined with an alignment setting?)
1. Switch to this branch
2. Test the Price block
=> Update price block to use placeholder and large font size

.distignore, src/blocks/list-container/edit.js
#63 refactored how we pass block attributes from the parent Curated List block to its inner list container and individual listing blocks by automatically setting attributes for its children directly. However, the list container block is still attempting to look up attributes from its parent instead of using its own synced attributes, which results in a JS error in certain situations.
Slightly related, I also removed the condition for the parent block needing to be selected in order to show a block appender button, which is something that used the faulty logic but we shouldn't need to refactor because we've already removed the condition in phase 2 PRs.
Somewhat difficult to replicate locally, as a curated list in query mode needs have been created on a plugin build prior to #63. Then, …
=> fix: use synced attributes for ListContainer directly

src/editor/shadow-taxonomies/index.js
Certain post types (read: Reusable Blocks) don't return a `meta` object when using `getEditedPostAttribute( 'meta' )`. This fixes a hard editor crash for post types like this.
1. On `epic/phase-2`, edit a Reusable Block. Observe an error message that prevents the editor from loading:
2. Check out this branch, refresh the editor, and confirm that the crash no longer happens.
=> fix: shadow taxonomy sidebar on post with no meta

src/blocks/list-container/edit.js
#73 removed the requirement for Curated List to be selected before its child list container's block appender button can appear, but it removed a bit too much. The condition should match https://github.com/Automattic/newspack-listings/blob/epic/phase-2/src/blocks/list-container/edit.js#L96:
```
renderAppender={ () => ( queryMode ? null : <InnerBlocks.ButtonBlockAppender /> ) }
```
=> fix: missing condition for block appender in list container

includes/class-newspack-listings-core.php, includes/newspack-listings-utils.php
This walks back a "feature" established in phase 2 which lets editors choose a post template (default, single feature, or single wide) if using a Newspack theme. As initially implemented, listings will default to whatever is set in the Customizer as the default post template; however, because v1 of Listings defaulted to single wide, this causes preexisting listings to change to whatever is set in the customizer. This PR defaults all listings to single wide, so will not cause any changes to the templates for preexisting listings, but still allows the template to be updated per listing.
Closes https://github.com/Automattic/newspack-listings/issues/76#issuecomment-865363365.
1. While on `master`, create some listings of any type. Observe that there's no "Post Attributes" sidebar panel for …
=> fix: default listings to one-column-wide.php post template

includes/class-newspack-listings-core.php, includes/class-newspack-listings-taxonomies.php, includes/importer/class-newspack-listings-importer.php, includes/migration/class-newspack-listings-migration.php, newspack-listings.php
Fixes and improvements coming from feedback from the v2 beta test. Related issues reported in #76.
In v2+ of Listings, listing CPTs use regular post categories and tags instead of separate custom taxonomies. We have a utility in place to check for and convert those legacy custom taxonomies, but it's an expensive operation. This PR avoids running the legacy term conversion script on every `admin_init` hook. Instead, moves the conversion to a WP CLI command so it has to be executed manually.
Addresses https://github.com/Automattic/newspack-listings/issues/76#issuecomment-867135473.
1. On `master`, create some legacy Listing Categories and Listing Tags and assign to some listings.
2. Check out this branch.
3. Run `wp newspack-listings taxonomies convert --dry-run` while SSHed into your test …
=> fix: memory leaks from legacy term utilities

includes/class-newspack-listings-blocks.php, src/assets/shared/listing.scss, src/blocks/curated-list/editor.scss, src/editor/utils.js
While testing another unrelated theme in WP 5.8, I discovered that Listings causes several errors and visual bugs in the new blocks-based Widgets screen. These changes should fix those issues.
1. Update WP to v5.8. The easiest way to do this is to install the [WordPress Beta Tester plugin](https://wordpress.org/plugins/wordpress-beta-tester/), go to Tools > Beta Testing, then set your site's update channel to "Bleeding Edge" then stream option to "Beta/RC only". Then go to Updates and update to a v5.8.x version.
2. Go to Appearance > Widgets. On `master` observe several PHP and JS errors that prevent the screen from rendering at all. e.g.
```
PHP Notice:  Trying to get property 'labels' of non-object in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-listings/includ …
```
=> fix: errors and bugs related to WP 5.8

src/blocks/listing/listing.js, src/editor/shadow-taxonomies/child-listings.js, src/editor/shadow-taxonomies/parent-listings.js
Fixes a bug reported by a publisher that occurs in Reusable Blocks. This is similar to #66 but with related content JS.
Also fixes an unrelated minor bug with the display of multiple categories in the editor.
1. On `master`, go to Posts > Reusable Blocks and edit a reusable block.
2. Observe a JS console error similar to this (sometimes this will result in a hard editor crash, too):
```
An error occurred while running 'mapSelect': meta is undefined
```
3. Check out this branch, rebuild, refresh the reusable block. Confirm there's no longer a JS error or editor crash.
4. Add a Curated List block to the reusable block, insert the reusable block into a post, update the reusable block from the post, and confirm that all works as expected.
1. Publish at least one listing with multiple …
=> fix: editor errors with reusable blocks

src/editor/index.js
Avoids potential JS errors and crashes in the new WP 5.8 widget blocks editor by not registering editor sidebars that assume we're in a post editor context.
This is somewhat difficult to test because it doesn't happen on every site nor even on every page load of every site it does happen on. [Here's a site where I saw it happening](https://wp58test-yubanet.newspackstaging.com/wp-admin/widgets.php) (ping me for credentials). But here's how you'd confirm the fix:
1. On `master`, on a site running WP 5.8, visit **Appearance > Widgets**. Observe several JS console errors like this which prevent the widgets UI from loading:
```
The above error occurred in the <WithDispatch(ChildListingsComponent)> component:
in WithDispatch(ChildListingsComponent)
in Unknown (created by …
```
=> fix(wp-5.8): do not register post-specific sidebars in widgets page

includes/class-newspack-listings-core.php
Avoids an error that prevents you from being able to update a listing post when certain blocks are present in the listing content. This stems from a failure to validate meta values against the REST schema when the synced values contain objects that might have unknown properties.
Some background: we look for certain blocks in listing content and sync their attributes to post meta. This is for the planned Phase 3 automated directory functionality; we need certain block attributes (such as locations, email addresses, phone numbers, etc.) to be easily queryable for front-end searching and filtering functionality. We implemented this sync early on so that we wouldn't have to go back to generate this data for listings that predate Phase 3. However, because in some cases we're saving all block …
=> fix: avoid meta sync update error

src/blocks/curated-list/edit.js, src/components/sidebar-query-controls.js
Bumps the max of number of listings that can be loaded at a time in a single Curated List block from 20 to 50.
Closes #94.
1. Insert a Curated List block in Query mode.
2. Under Query Settings, confirm that the "Max number of items" range control now allows the option to be set from 1–50.
3. Confirm that the number of posts shown in the list at a time matches the setting in the editor and on the front-end (and that when using "Load more" functionality, the pagination is batched by this same number).
=> feat: bump max number of items per list from 20 to 50

includes/class-newspack-listings-core.php, includes/newspack-listings-utils.php, src/blocks/listing/listing.js, src/editor/utils.js, src/templates/listing.php
Adds class names for each category, tag, and the listing post type whenever listings are shown in the following contexts:
* In Curated Lists on the `article` element for each listing item, in both the editor and on the front-end
* In Homepage Posts and Post Carousel blocks on the `article` or `div` element for each listing item, in both the editor and on the front-end (requires https://github.com/Automattic/newspack-blocks/pull/819)
* On single listing posts, on the `body` element
This should make it easier for publishers to apply custom CSS for specific categories, tags, or listing post types. An example use case would be if there were a tag called "Best of" that could be applied to any listing; all listings with that tag should show a custom "Best of" flag wherever they appear on the …
=> feat: show classes for each category and tag on every listing

src/blocks/event-dates/edit.js
Satisfy the `DatePickerComponent` `onMonthPreviewed` dependency with a `noop`.
Closes #104.
1. On master branch, attempt to change the month of an event and see the block crashing
2. Switch to this branch, build and observe that you can switch months without crashing
=> fix: satisfy DatePicker prop dependency

includes/class-newspack-listings-core.php
This PR adds a CSS class to the body, each when the date or author is hidden on a listing.
It's one possible way to fix https://github.com/Automattic/newspack-theme/issues/1389. This is only needed to fix an issue in Newspack Sacha, so I'm open to alternative approaches; I also only added these classes to the plugin because I saw others related to the theme there, but if it's better to add to the theme, just let me know!
1. Apply the PR. 
2. Try hiding the date and author on a site-wide level under WP Admin > Listings > Settings; confirm each setting adds either a `hide-date` or `hide-author` body class.
3. Try toggling the hide date/author options on a per-listing level and confirm they affect which body classes appear (eg. if you have the date hidden site-wide, but set to show on one …
=> feat: add CSS classes for hidden date, author

.distignore, includes/class-newspack-listings-api.php, includes/class-newspack-listings-core.php, includes/class-newspack-listings-settings.php, includes/importer/class-newspack-listings-importer.php, src/templates/listing.php
Some minor tweaks and importer script updates for the GDG migration. Also, because of a bug in some GDG-specific code, the site launched with listing permalinks set without a `listing` URL prefix. Setting an empty prefix is currently impossible in Listings settings UI, so this PR updates the UI to allow such a situation.
Closes #111.
Some background context: originally, the `listings` URL prefix (or a user-defined prefix) was a requirement to avoid potential conflicts with other plugins' permalink settings. Specifically, The Events Calendar uses `events` as the permalink slug for their Events CPT, so the Newspack Listings Events CPT with a permalink slug of `events` would have the same permalink structure as TEC post types, meaning permalinks for one or the other post type would always …
=> feat: allow empty prefix slug; tweaks for GDG import

includes/class-newspack-listings-products.php, includes/class-newspack-listings-settings.php, newspack-listings.php
Takes the first step toward self-serve listings with some automated WooCommerce products to help facilitate single purchase or subscription-based listings.
The following products are included to start, but all of these are subject to change based on publisher feedback. The default prices and planned behavior are also subject to change pending publisher feedback.
* **Single Listing:** Users can purchase a single listing of any type (Event, Generic, Marketplace, or Place).
- **Intended behavior (not yet implemented):** Once a user purchases a single listing, they can edit their listing in the block editor and submit it for editorial review. Once approved and published by a staff member, the listing is live for 30 days. If they want to extend the life of the listing, the user can purchase …
=> feat(ugc): automated WC products for self-serve listings

includes/class-newspack-listings-products.php
Fixes a fatal error with dire consequences, triggered by certain conditions.
Closes #121.
1. On `master`, set `define( 'NEWSPACK_LISTINGS_SELF_SERVE_ENABLED', true );` in your wp-config.php file.
2. Install and activate WooCommerce, but not WooCommerce Subscriptions (disable this latter plugin if already installed and active).
3. Refresh the site and observe a fatal error which prevents the entire site from loading—admin and front-end! 😱 
4. Check out this branch, confirm that the fatal is avoided and that the Self-Serve Listings features are only enabled if both WooCommerce and WooCommerce Subscriptions are active.
=> fix: fatal error when WooCommerce Subscriptions is not active

src/blocks/event-dates/edit.js, src/blocks/event-dates/editor.scss
Fixes a crash in the `DatePicker` component that was [introduced in WP 5.8](https://github.com/WordPress/gutenberg/pull/29716). It's been [fixed in the Gutenberg plugin](https://github.com/WordPress/gutenberg/pull/31751) but apparently not yet in WP Core. This fix avoids the use of `DatePicker` and uses `DateTimePicker` (which isn't affected by this bug) even when not using times in the block.
1. Ensure your test site is running WP 5.8+ but NOT the Gutenberg plugin.
2. On `master`, create an Event listing. In the Event Date block, **disable** "Show Times" and **enable** "Show End Date".
3. Attempt to change the month of the end date and observe a JS crash: `TypeError: t.onMonthPreviewed is not a function`
4. Check out this branch, repeat steps 1-2, confirm that the crash is avoided and …
=> fix: editor crash when switching months in event dates block

includes/class-newspack-listings-core.php, includes/class-newspack-listings-settings.php, includes/newspack-listings-utils.php, src/assets/front-end/archives.scss, src/assets/front-end/view.scss
Ports some of the lower-risk feature enhancements developed for GDG back into the main Listings plugin. These new features are gated behind new settings so that sites that are already using Listings won't see any unexpected behavior.
I'd also like to port the "featured listing" functionality from GDG, but I'm awaiting some feedback on https://github.com/Automattic/newspack-gdg/issues/1 before we do so as it may impact performance in the current state.
1. Check out this branch; go to **Listings > Settings**.
2. Observe a new setting under the "Post Meta Settings" heading, disabled by default:
3. Enable it and save. Edit any listing and expand the "Categories" sidebar, and confirm that you can no longer choose a primary category.
1. Check out this branch; ensure that category/tag archives …
=> feat: feature extensions from gdg

includes/class-newspack-listings-featured.php
An experimental, alternative solution to re-sorting post queries to show featured listings in descending order of priority number before other posts. This branch creates a custom DB table with just two columns: `post_id` and `feature_priority`. On post save, if the post is featured, the feature priority meta value is copied to a row with the same value, keyed to the post's ID. If it's not featured, any rows matching the post's ID in the custom table are deleted, which should hopefully keep the table lean. On post query, matching rows are appended to the main posts query using a `LEFT JOIN` statement and then used as a sorting criterion. The theory is that this _should_ be more performant than using post meta to sort the query, but I'm not 100% certain it is, hence the experimental nature …
=> feat: featured listing query sorting via custom table instead of post meta

includes/class-newspack-listings-core.php, includes/class-newspack-listings-settings.php
Adds a new setting to optionally prevent the Jetpack Related Posts module from appearing on singular listings. This is turned on by default as it's been a very common request from publishers.
Closes #115.
This is a hard feature to test because you need a site that is connected to and has been fully indexed by Jetpack (basically, a true production site). The Related Posts module also needs to have been turned on for some time after that before it will start appearing on the site. DM me if you're having trouble finding a suitable site to test with.
1. On `master`, on a site which is displaying the Related Posts module, observe that the module appears on singular posts of all types, including listings.
2. Check out this branch; go to **Listings > Settings**. Confirm there's a new option …
=> feat: add new setting to disable Jetpack Related Posts module

.circleci/config.yml, tests/test-featured.php
As seen on https://github.com/Automattic/newspack-ads/pull/214, recent changes made to `circleci/php` resulted in our builds fail due to an incompatibility with our `node-sass` dependency.
[`circleci/` images are being deprecated and will lose support starting December 2021](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034). We should start moving towards maintained images.
This PR implements the use of `cimg/` images.
CI tasks must pass.
=> fix: update ci images

.circleci/config.yml
Fixes a typo on the CI release task.
CI tasks must pass.
=> fix: ci build command typo

includes/class-newspack-listings-core.php, includes/class-newspack-listings-featured.php, includes/class-newspack-listings-settings.php
Fixes two minor bugs related to featured and self-serve listings. Also adds a filter that lets external plugins define whether specific archive pages or other queries should show listing post types.
This one is hard to test unless you had the very experimental version of featured listings enabled. But the experimental version used post meta for feature priority, whereas the new treatment uses a custom table value. The plugin migrates featured listings to the custom table, but previously didn't check the priority value—it just set all listings to the default priority.
1. Using WP CLI, simulate the conditions of migrating from a site using the very experimental version of featured listings by adding a meta value to a listing post: `wp post meta update <listing ID> …
=> fix: minor bugfixes for featured and self-serve listings

includes/class-newspack-listings-blocks.php
Fixes a fatal error that occurs in the block editor when the `NEWSPACK_LISTINGS_SELF_SERVE_ENABLED` environment variable is not defined or not `true`. 😢 
1. In your `wp-config.php`, define `NEWSPACK_LISTINGS_SELF_SERVE_ENABLED` as false or remove the constant entirely from your config.
2. On `master`, observe that any and all block editor pages fail to load with a fatal PHP error.
3. Check out this branch, refresh the editor, confirm that the error no longer occurs.
4. Define `define( 'NEWSPACK_LISTINGS_SELF_SERVE_ENABLED', true );` in your config and confirm that the editor still works, and that self-serve and featured listing features are now available.
=> [URGENT] fix: a fatal error when self-serve listings env variable is not defined

src/blocks/listing/listing.js
Fixes a minor bug in the editor UI for Curated List blocks. The front-end isn't affected, just the editor. Note: this may or may not require WP 5.9 to replicate.
1. Publish several listings, some with categories applied and others with no categories.
2. Add a Curated List block to a post and set its query settings to show your listings with and without categories.
3. Enable the "Show Categories" option for the Curated List block.
4. Observe that the listings without any categories display a `0` in place of the category labels:
5. Check out this block, refresh, confirm that the `0` no longer appears.
=> fix: prevent showing 0 for listings with no categories

package-lock.json, package.json
Resolves a build issue.
`newspack-scripts` uses PostCSS v8, but an indirect dependency must be setting it to a lower version. Requiring v8 explicitly resolves a build issue.
1. On `master`, try to build (`npm run build`)
2. Observe it logging warnings about PostCSS usage
3. Switch to this branch, build again, observe building without issues
=> fix: require postcss explicitly

includes/class-newspack-listings-api.php
The feature to sort event listings by event date isn't quite working. I believe it's because the query tries to sort by the `newspack_listings_event_start_date` meta value, and treats this meta value as a `dateetime` string. However, this meta field saves datetime strings as plain text strings, e.g. `2022-03-04T17:30:00`. When sorting a curated list block containing events by event date, and multiple events have event dates that start on the same date but at different times, the sorting order isn't always correct—`2022-03-04T17:30:00` ends up being sorted after `2022-03-04T19:15:00` despite being a later time.
This PR updates the query sorting to treat the meta values as plain text so that `2022-03-04T17:30:00` should come before `2022-03-04T19:15:00`.
1. Publish at least two Event …
=> fix(curated-list): when sorting by event date, treat date strings as plain strings

includes/class-newspack-listings-products.php
In WP 5.9, FSE implements several new capabilities checks in the block editor that gate access to certain block editor features, notably the featured image sidebar panel and reusable blocks inserter. These checks are performed via REST API, so the server `$_REQUEST` params we're currently using to decide whether the user is viewing a block editor page don't apply to these requests. This means that self-serve listing customers currently can't edit or view featured images for their own listings.
However, the capabilities checks via REST API do seem to include a `context` argument, which is either `view` or `edit`. If this argument exists and is `edit`, we can reasonably assume the request is coming from a REST API request to check editor permissions and allow or deny permissions …
=> fix: allow customers to access block editor components

CHANGELOG.md, includes/class-blocks.php, newspack-listings.php, package-lock.json, package.json, src/editor/index.js
#233 simplified the checks to determine whether to allow self-serve and featured listings to be managed in the dashboard, but it perhaps simplified them a bit too much. It's possible that a site might want to use featured listings but not self-serve, in which case they might not need WooCommerce or WooCommerce Subscriptions, which are prerequisites for self-serve but not featured listings. This PR restores the separate checks for each so that featured listings can still be used even if those plugins aren't active.
1. On your test site, disable WooCommerce and/or WooCommerce Subscriptions. Set `define( 'NEWSPACK_LISTINGS_SELF_SERVE_ENABLED', true );` in your `wp-config.php`.
2. Edit a listing and observe that the Featured Listing sidebar is not available.
3. Check out this branch and …
=> fix: separate checks for self-serve vs. featured listings

composer.json, src/assets/shared/self-serve-listings.scss, src/blocks/self-serve-listings/block.json, src/blocks/self-serve-listings/edit.js, src/templates/self-serve-form.php
The self-serve purchase form currently allows disabling subscription purchases, but not single listing purchases. This PR allows editors to choose whether the self-serve block should allow single listings, subscription listings, or both. It deprecates the legacy `allowSubscription` boolean block attribute by treating it as a `single-only` value for `allowedPurchases`.
Related to #145.
1. On `master`, add a self-serve listings block to a post or page. Turn off the toggle for "Allow subscriptions".
2. Check out this branch and refresh the editor. Confirm that the block display doesn't change in either the editor or on the front-end, and that it's not showing the "Listing Subscription" tab.
3. Select the block in the editor and confirm that the "Allow subscriptions" toggle is replaced by a …
=> feat(self-serve): enable subscription-only self-serve purchase forms

includes/class-featured.php, tests/test-featured.php
Currently, feature priority is set in a custom DB table that's used to sort featured listings first. This table is updated when a featured listing is generated automatically (such as via self-serve purchase), as well as when the priority value is changed in the WP block editor. The priority value is automatically deleted (and the featured status toggled off) via cron job if the listing's featured expiration date passes.
However, the priority value is currently NOT updated if you simply manually toggle on the Featured status for a listing in the block editor without altering the default priority value of 5. This PR fixes that, and also ensures that the priority data is deleted on save after manually toggling OFF the featured status in the block editor.
This PR also bumps the value of the …
=> fix(featured): set or unset featured status on manual post save

includes/class-core.php
If sharing buttons are enabled in Jetpack, allow them to appear on listings as well as posts/pages.
Closes #255.
1. Under **Jetpack > Settings > Sharing**,  enable sharing buttons:
2. On `master`, publish a listing and view it on the front-end. Observe that no share buttons are displayed.
3. Check out this branch, refresh, and confirm that the share buttons are displayed and work exactly as they do for posts and pages.
4. Check the listing in both AMP and non-AMP modes.
=> feat: enable jetpack share buttons on listings

includes/class-settings.php
#256 deprecated and removed all features and settings for Related Listings. However, there's a somewhat-hidden feature in the plugin which uses one of the settings page sections for related content, so we need to restore that section when Jetpack's Related Posts module is turned on.
1. On `master`, turn on Jetpack's Related Posts module (**Jetpack > Settings > Traffic**).
2. Go to **Listings > Settings** and observe a PHP warning in debug.log:
```
Notice: Undefined index: related in /srv/htdocs/wp-content/plugins/newspack-listings/includes/class-settings.php on line 163
Notice: Trying to access array offset on value of type null in /srv/htdocs/wp-content/plugins/newspack-listings/includes/class-settings.php on line 163
```
3. Check out this branch, refresh the Newspack Listings settings …
=> fix: restore Related Content settings section, but only if Jetpack Related Posts is on

.circleci/config.yml, CHANGELOG.md, includes/class-featured.php, newspack-listings.php, package-lock.json, package.json
Up til now, all Newspack clients who use featured listings either use or are experimenting with self-serve features, so the two feature sets were gated behind a single `NEWSPACK_LISTINGS_SELF_SERVE_ENABLED` environment constant. 
This fix allows featured listings to be enabled without also enabling self-serve listings. The two featuresets work independently, but self-serve listings require featured listings to be enabled, so the `NEWSPACK_LISTINGS_SELF_SERVE_ENABLED` constant alone will still enable both featuresets. But now, a `NEWSPACK_LISTINGS_FEATURED_ENABLED` constant will enable only featured listings and not self-serve listings.
1. Check out this branch and ensure your `wp-config.php` file does not have either the `NEWSPACK_LISTINGS_SELF_SERVE_ENABLED` or …
=> fix: allow featured listings features to be enabled independently of self-serve

includes/class-api.php, includes/class-featured.php, src/blocks/curated-list/edit.js, src/blocks/listing/edit.js, src/editor/utils.js
Adds support for featured listings class names and query sorting to Curated List blocks. Closes #282.
1. Publish some listings and make some (but not all) of them featured.
2. Add a Curated List block to a post or page and set it to Query mode.
3. Confirm that the featured listings appear at the top of the query, in feature priority order, and that the listing elements in the DOM have feature-related class names, both in the editor and on the front-end.
=> feat: add featured listing support to curated lists

src/blocks/curated-list/block.json, src/blocks/curated-list/view.php
This PR makes sure the Curated List block applies custom CSS classes to the front-end.
Closes #278.
1. Add a Curated List block in the editor, and give it a custom CSS class under the Advanced panel in the right sidebar.
2. Publish the page.
3. Inspect the Curated List block on the front-end; note that your CSS class is not being output (it should be on the outer most element of the block, with the CSS class `newspack-listings__curated-list`. 
4. Apply the PR.
5. Refresh the page; confirm that the block now shows up.
=> Curated List: make sure custom CSS classes are output

includes/class-blocks.php
This PR removes the check before loading the Curated List block styles. 
Originally the plugin checked if the block existed in the page content before loading the styles. This meant the styles weren't loading if the block was only inserted into a widget space on the page, or in a reusable block.
We should be able to fix the widget issue with a similar check, but the reusable block bit is trickier -- the blocks inside of a reusable block don't exist in a page's content the same way as adding a regular block directly to the editor.
Though this means loading more CSS, I think this is the best fix for now; it could be worth trying to solve the reusable block question, though, and if it is possible to do, it could be worth moving to our block plugin, too. 
(@dkoo if you'd rather try to resolve …
=> fix: remove content check before loading Curated List styles

includes/class-blocks.php, includes/class-products.php, includes/class-settings.php, src/blocks/self-serve-listings/view.php
When self-serve listings are enabled, the plugin automatically generates the required WooCommerce products it needs to enable the reader-facing purchase flow. However, if any of these products is unpublished or deleted, the plugin will regenerate them, potentially resulting in many unwanted duplicates.
This PR removes the auto-generation and instead requires an intentional action on the part of site admins to create the products before self-serve features can be used. It also allows for deletion of the products (thus disabling self-serve purchase features) if self-serve isn't needed on the site.
The UI is fairly bare-bones as self-serve features are still experimental, but this does prevent a situation where unwanted products can be created en masse.
1. On a new site, install this plugin, …
=> fix: prevent dupes of self-serve products; manual creation and deletion

includes/products/class-products-user.php, src/editor/index.js
`__experimentalMainDashboardButton` is being [deprecated](https://github.com/WordPress/gutenberg/pull/45149), so this PR removes it in favor of a more generalized solution to redirect to the My Account dashboard whenever a listings customer tries to access a page they don't have permissions for.
1. Check out this branch.
2. Log in as a listings customer, or complete a purchase for a self-serve listing product via the self-serve listings block.
3. Try to access any restricted WP admin page, such as a posts list (`/edit.php?post_type=page`). Confirm that you're redirected to the main My Account dashboard.
=> refactor: remove use of __experimentalMainDashboardButton

includes/class-products.php, includes/products/class-products-purchase.php, includes/products/class-products-ui.php
Similar to https://github.com/Automattic/newspack-popups/pull/1013, replaces the soon-to-be-deprecated `FILTER_SANITIZE_STRING` with `FILTER_SANITIZE_FULL_SPECIAL_CHARS` in anticipation of PHP 8.1.
No functional changes, but when running the plugin on PHP >= 8.1, the following warnings on `master` should be fixed:
```
PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-listings/includes/products/class-products-purchase.php on line 66
```
```
PHP Deprecated:  urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-listings/includes/products/class-products-ui.php on line 536
```
=> chore: handle PHP 8.1 deprecation

postcss.config.js
Removes the `postcss.config.js` file, which is not used. `newspack-scripts`'s PostCSS config is used when building CSS.
=> chore: remove unused config file

includes/class-core.php, includes/class-featured.php, includes/utils.php
The Listings editor UI stores expiration date meta fields in `YYYY-MM-DDT00:00:00` format, but this field can sometimes be populated by other automations in different formats.
Instead of expecting all expiration date meta fields to be in `YYYY-MM-DDT00:00:00` format, this fix now allows this meta field to be stored in any valid date string format which can be converted to UNIX time using [`strtotime`](https://www.php.net/manual/en/function.strtotime.php).
Closes `1203869877018965/1204006619447975`.
1. Publish a listing of any time and set the publish date to sometime in the past.
2. Using WP CLI, set the expiration date meta field to a date string in the more recent past but that's not the expected format: `wp post meta update [post ID] newspack_listings_expiration_date '2023-02-13 …
=> fix: accommodate any valid date string in newspack_listings_expiration_date

newspack-listings.php
Looks like the `NEWSPACK_LISTINGS_VERSION` constant got out of sync with CI and hasn't been getting updated. This is resulting in assets not getting their cache busted properly.
Check out this branch, edit a listing, and confirm that the `editor.js` and `editor.css` files from this plugin have a `?ver=2.12.3` cache param.
=> fix: manually bump asset version so CI can pick it up again

.hooks/pre-push, composer.json, package.json
Prevents direct pushes to master.
1. Run composer install
2. Commit something to master
3. try to push and see the error message
=> fix: add pre push hook

includes/class-products.php
If self-serve listings features are not enabled, the `Products` class will still run some of its actions, which can result in errors in some cases. This PR prevents those actions from running if self-serve features are disabled.
1. Make sure your `wp-config.php` does not have the `NEWSPACK_LISTINGS_SELF_SERVE_ENABLED` constant, or that it's set to `false`.
2. On `release`, add an `error_log( 'test' )` line to output something in the `update_products` method [here](https://github.com/Automattic/newspack-listings/blob/master/includes/class-products.php#L299).
3. Go to Listings > Settings and save. Observe that your `error_log` executes even though self-serve features are disabled.
4. Check out this branch and repeat step 3. Confirm that the method does not execute now unless the …
=> fix: only run self-serve-related actions if enabled

languages/newspack-listings.pot
This PR adds a POT file to the Newspack Listings plugin.
See 1200550061930446-as-1204498431816519
1. Apply the PR.
2. Confirm the plugin has a /languages/newspack-listings.pot file.
3. Bonus: install and activate the [Loco Translate](https://wordpress.org/plugins/loco-translate/) plugin, and navigate to WP Admin > Loco Translate > Plugins in the left sidebar, and confirm the Listings plugin is available and can be translated.
=> feat: add POT file to Listings plugin

src/templates/event-dates.php
This PR adds `date_i18n()` to the event listing dates, so they'll update when the site changes languages.
See 1200550061930446-as-1204498431816519
1. Apply the PR. 
2. Create a few event listings with different formats: just one date and a start and end date, and show or hide the times.
3. Confirm that the dates look as expected on the front-end.
4. Change the site's language under WP Admin > Settings > General.
5. Confirm that the date now picks up your site's new language.
=> feat: add internationalization to event dates

includes/class-settings.php, src/templates/event-dates.php
This PR adds an option to change the four front-facing date formats used by the Events post type:
* The full event date
* The full event time
* Two partial event dates, to reduce duplication (one without the year, and one without the month)
This change improves the ability to translate the event date, on top of #391, since date and time formats often need to change to properly translate them. 
See 1200550061930446-as-1204498431816519
1. Apply the PR.
2. Create a few event posts. 
3. Navigate to WP Admin > Listings > Settings; confirm there is now a section that allows you to change the event date format, and that it uses the plugin's original defaults:
4. Try changing the date and time formats; confirm that they're picked up by single Events and Events displayed in the Curated Listings …
=> feat: add option to change the event date/time format

languages/newspack-listings.pot, newspack-listings.php
Updates some lingering legacy URLs throughout the code. All instances of newspack.pub or newspack.blog should be newspack.com
No functional changes.
=> chore: newspack.pub > newspack.com

composer.lock, languages/newspack-listings.pot, newspack-listings.php, package-lock.json, package.json
=> Alpha release Oct 16
